export const actionTypes = {
  AUTH_USER: 'AUTH_USER',
  AUTH_ERROR_MSG: 'AUTH_ERROR_MSG',
  RESET_ERROR: 'RESET_ERROR',
  SWITCH_DARKMODE: 'SWITCH_DARKMODE',
  THEME_ERROR_MSG: 'THEME_ERROR_MSG',
};
